# Generated by Django 3.0.8 on 2020-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('3d', '3D'), ('2d', '2D'), ('addons', 'Add-on'), ('rigged_models', 'Rigged Models'), ('essentials', 'Essentials'), ('gui', 'GUI'), ('templates', 'Templates'), ('audio', 'Audio'), ('tools', 'Tools'), ('vfx', 'VFX')], max_length=25)),
                ('moved_to_general', models.DateTimeField(null=True)),
            ],
        ),
    ]
