# Generated by Django 3.0.8 on 2020-08-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200804_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
