# Generated by Django 3.1 on 2020-08-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200806_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('-creation_date', 'name')},
        ),
    ]
