# Generated by Django 3.0.8 on 2020-08-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20200806_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(to='assets.Tag'),
        ),
    ]
