# Generated by Django 3.1 on 2020-08-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('ready', 'Ready'), ('building', 'Building')], max_length=10, null=True)),
                ('description', models.TextField(max_length=700, null=True)),
                ('active_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('assets', models.ManyToManyField(to='assets.Asset')),
            ],
            options={
                'ordering': ('-creation_date', 'status'),
            },
        ),
    ]
